version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5556:5432"
    volumes:
      - D:/docker_postgresql/data:/var/lib/postgresql/data 

volumes:
  pgdata:
